name: Atualizar Lista Vavoo

on:
  schedule:
    - cron: '0 */2 * * *'   # a cada 2 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Definir timezone UTC
        run: sudo timedatectl set-timezone UTC

      - name: Instalar dependências
        run: pip install --no-cache-dir requests

      - name: Gerar Lista M3U
        run: python vavoo.py

      - name: Commit e Push (se houver alterações)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            git add lista.m3u
            git commit -m "Atualiza lista.m3u"
            git push
          else
            echo "Nenhuma alteração para commitar"
          fi
